In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv("boston.csv")

In [6]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM        AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.199997  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.900002  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.099998  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.799999  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.200001  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...        ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.099998  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.699997  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.000000  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.300003  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.800003  2.5050    1  273   

            PT           B  LSTAT         MV  
0    15.300000  396.899994   4.98  24.000000  
1    17.799999  396.899994   9.14  21.600000  
2    17.799999  392.829987   4.03  34.700001  
3    18.700001  394.630005   2.94  33.400002  
4    18.700001  396.899994   5.33  36.200001  
..         ...         ...    ...        ...  
501  21.000000  391.989990   9.67  22.400000  
502  21.000000  396.899994   9.08  20.600000  
503  21.000000  396.899994   5.64  23.900000  
504  21.000000  393.450012   6.48  22.000000  
505  21.000000  396.899994   7.88  11.900000  

[506 rows x 14 columns]

# Linear Regression

In [7]:
from sklearn.metrics import mean_squared_error, r2_score

In [8]:
from sklearn.model_selection import train_test_split
df=data

In [9]:
df["CRIM"]= (df["CRIM"] - df["CRIM"].min())/(df["CRIM"].max()- df["CRIM"].min())
df["RM"]= (df["RM"] - df["RM"].min())/(df["RM"].max()- df["RM"].min())
df["AGE"]= (df["AGE"] - df["AGE"].min())/(df["AGE"].max()- df["AGE"].min())
df["LSTAT"]= (df["LSTAT"] - df["LSTAT"].min())/(df["LSTAT"].max()- df["LSTAT"].min())
df["RAD"]= (df["RAD"] - df["RAD"].min())/(df["RAD"].max()- df["RAD"].min())

In [15]:
training_features = [ 'CRIM','RM','AGE','LSTAT','RAD']
target = 'MV'
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.15,  #0.1 to 0.2
                                                   random_state=17)  #random state 1 to 10000

In [16]:
from sklearn import linear_model
model = linear_model.LinearRegression()
from sklearn.linear_model import SGDRegressor
#model = SGDRegressor(alpha=0.02) #alpha 0.001 to 0.1
#model = linear_model.Ridge(alpha=10.0)
#model = linear_model.Lasso(alpha=1.0)
#from sklearn.neighbors import KNeighborsRegressor
#model = KNeighborsRegressor(n_neighbors=4,p=2,weights='distance') #weights -uniform or p = 2

In [17]:
model.fit(X_train,Y_train)

LinearRegression()

In [18]:
predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

Mean squared error: 19.30
R Square score: 0.70


In [19]:
# The coefficients
print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)

Coefficients: 
 [ -6.98622114  25.80918748   1.46445255 -23.27731451  -0.53500916]
Intercept:
 15.717515331348114


# SGD

In [36]:
training_features = [ 'CRIM','RM','AGE','LSTAT','RAD']
target = 'MV'
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.12,  #0.1 to 0.2
                                                   random_state=41)  #random state 1 to 10000

In [37]:
from sklearn import linear_model
#model = linear_model.LinearRegression()
from sklearn.linear_model import SGDRegressor
model = SGDRegressor(alpha=0.02) #alpha 0.001 to 0.1
#model = linear_model.Ridge(alpha=10.0)
#model = linear_model.Lasso(alpha=1.0)
#from sklearn.neighbors import KNeighborsRegressor
#model = KNeighborsRegressor(n_neighbors=4,p=2,weights='distance') #weights -uniform or p = 2

In [38]:
model.fit(X_train,Y_train)

SGDRegressor(alpha=0.02)

In [39]:
predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

Mean squared error: 19.08
R Square score: 0.61


In [40]:
# The coefficients
print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)

Coefficients: 
 [ -2.11234515  16.26773888  -1.86606804 -14.92812425  -2.88838283]
Intercept:
 [20.98185959]


# ridge

In [54]:
training_features = [ 'CRIM','RM','AGE','LSTAT','RAD']
target = 'MV'
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.11,  #0.1 to 0.2
                                                   random_state=99)  #random state 1 to 10000

In [55]:
from sklearn import linear_model
#model = linear_model.LinearRegression()
from sklearn.linear_model import SGDRegressor
#model = SGDRegressor(alpha=0.02) #alpha 0.001 to 0.1
model = linear_model.Ridge(alpha=5.0)
#model = linear_model.Lasso(alpha=1.0)
#from sklearn.neighbors import KNeighborsRegressor
#model = KNeighborsRegressor(n_neighbors=4,p=2,weights='distance') #weights -uniform or p = 2

In [56]:
model.fit(X_train,Y_train)

Ridge(alpha=5.0)

In [57]:
predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

Mean squared error: 19.85
R Square score: 0.70


In [58]:
# The coefficients
print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)

Coefficients: 
 [ -3.97556457  18.48424485  -0.55315158 -18.64567595  -2.07567357]
Intercept:
 19.754143054259345


# Lasso

In [64]:
training_features = [ 'CRIM','RM','AGE','LSTAT','RAD']
target = 'MV'
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.12,  #0.1 to 0.2
                                                   random_state=75)  #random state 1 to 10000

In [65]:
from sklearn import linear_model
#model = linear_model.LinearRegression()
from sklearn.linear_model import SGDRegressor
#model = SGDRegressor(alpha=0.02) #alpha 0.001 to 0.1
#model = linear_model.Ridge(alpha=10.0)
model = linear_model.Lasso(alpha=1.0)
#from sklearn.neighbors import KNeighborsRegressor
#model = KNeighborsRegressor(n_neighbors=4,p=2,weights='distance') #weights -uniform or p = 2

In [66]:
model.fit(X_train,Y_train)

Lasso()

In [67]:
predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

Mean squared error: 51.56
R Square score: 0.26


In [68]:
# The coefficients
print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)

Coefficients: 
 [-0.          0.         -0.         -9.15583281 -0.        ]
Intercept:
 25.300844136606788


# KNN

In [69]:
training_features = [ 'CRIM','RM','AGE','LSTAT','RAD']
target = 'MV'
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.12,  #0.1 to 0.2
                                                   random_state=755)  #random state 1 to 10000

In [70]:
from sklearn import linear_model
#model = linear_model.LinearRegression()
from sklearn.linear_model import SGDRegressor
#model = SGDRegressor(alpha=0.02) #alpha 0.001 to 0.1
#model = linear_model.Ridge(alpha=10.0)
#model = linear_model.Lasso(alpha=1.0)
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=4,p=2,weights='distance') #weights -uniform or p = 2

In [71]:
model.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=4, weights='distance')

In [72]:
predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

Mean squared error: 16.70
R Square score: 0.87
